-- MySQL Script generated by MySQL Workbench
-- Sat 24 Jan 2015 10:13:01 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema meteocal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema meteocal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `meteocal` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `meteocal` ;

-- -----------------------------------------------------
-- Table `meteocal`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meteocal`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `given_name` VARCHAR(45) NOT NULL,
  `family_name` VARCHAR(45) NOT NULL,
  `active` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meteocal`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meteocal`.`events` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `start` DATETIME NOT NULL,
  `end` DATETIME NOT NULL,
  `location` VARCHAR(255) NOT NULL,
  `public` TINYINT(1) NOT NULL,
  `outdoor` TINYINT(1) NOT NULL,
  `creator` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_events_users1_idx` (`creator` ASC),
  CONSTRAINT `event_ownership`
    FOREIGN KEY (`creator`)
    REFERENCES `meteocal`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meteocal`.`calendars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meteocal`.`calendars` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `owner` INT NOT NULL,
  `public` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_calendars_users1_idx` (`owner` ASC),
  UNIQUE INDEX `owner_UNIQUE` (`owner` ASC),
  CONSTRAINT `calendar_ownership`
    FOREIGN KEY (`owner`)
    REFERENCES `meteocal`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meteocal`.`participations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meteocal`.`participations` (
  `event` INT NOT NULL,
  `calendars_id` INT NOT NULL,
  `accepted` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`event`, `calendars_id`),
  INDEX `fk_events_has_users_events1_idx` (`event` ASC),
  INDEX `fk_event_participations_calendars1_idx` (`calendars_id` ASC),
  CONSTRAINT `events_participations`
    FOREIGN KEY (`event`)
    REFERENCES `meteocal`.`events` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `calendars_participations`
    FOREIGN KEY (`calendars_id`)
    REFERENCES `meteocal`.`calendars` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meteocal`.`notifications_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meteocal`.`notifications_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meteocal`.`notifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meteocal`.`notifications` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `events_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  `notifications_type` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_notifications_events1_idx` (`events_id` ASC),
  INDEX `fk_notifications_users1_idx` (`users_id` ASC),
  INDEX `fk_notifications_notifications_types1_idx` (`notifications_type` ASC),
  CONSTRAINT `event_notifications`
    FOREIGN KEY (`events_id`)
    REFERENCES `meteocal`.`events` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `user_notifications`
    FOREIGN KEY (`users_id`)
    REFERENCES `meteocal`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `notification_type`
    FOREIGN KEY (`notifications_type`)
    REFERENCES `meteocal`.`notifications_types` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meteocal`.`weather_conditions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meteocal`.`weather_conditions` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `icon` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meteocal`.`cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meteocal`.`cities` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `lat` DOUBLE NOT NULL,
  `lon` DOUBLE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meteocal`.`forecasts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meteocal`.`forecasts` (
  `dt` DATETIME NOT NULL,
  `city` INT NOT NULL,
  `temp_min` DOUBLE NOT NULL,
  `temp_max` DOUBLE NOT NULL,
  `pressure` DOUBLE NOT NULL,
  `humidity` DOUBLE NOT NULL,
  `weather_condition` INT NOT NULL,
  INDEX `fk_forecasts_weather_conditions1_idx` (`weather_condition` ASC),
  INDEX `fk_forecasts_cities1_idx` (`city` ASC),
  PRIMARY KEY (`dt`, `city`),
  CONSTRAINT `forecast_conditions`
    FOREIGN KEY (`weather_condition`)
    REFERENCES `meteocal`.`weather_conditions` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `city_forecasts`
    FOREIGN KEY (`city`)
    REFERENCES `meteocal`.`cities` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meteocal`.`events_forecasts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meteocal`.`events_forecasts` (
  `events_id` INT NOT NULL,
  `forecasts_city` INT NOT NULL,
  `forecasts_dt` DATETIME NOT NULL,
  PRIMARY KEY (`events_id`, `forecasts_city`, `forecasts_dt`),
  INDEX `fk_events_has_forecasts_forecasts1_idx` (`forecasts_city` ASC, `forecasts_dt` ASC),
  INDEX `fk_events_has_forecasts_events1_idx` (`events_id` ASC),
  CONSTRAINT `fk_events_has_forecasts_events1`
    FOREIGN KEY (`events_id`)
    REFERENCES `meteocal`.`events` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_events_has_forecasts_forecasts1`
    FOREIGN KEY (`forecasts_city` , `forecasts_dt`)
    REFERENCES `meteocal`.`forecasts` (`city` , `dt`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
