-- MySQL Script generated by MySQL Workbench
-- Sat 24 Jan 2015 10:13:01 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema meteocal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema meteocal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `meteocal` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `meteocal` ;

-- -----------------------------------------------------
-- Table `meteocal`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meteocal`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `given_name` VARCHAR(45) NOT NULL,
  `family_name` VARCHAR(45) NOT NULL,
  `active` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meteocal`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meteocal`.`events` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `start` DATETIME NOT NULL,
  `end` DATETIME NOT NULL,
  `location` VARCHAR(255) NOT NULL,
  `public` TINYINT(1) NOT NULL,
  `outdoor` TINYINT(1) NOT NULL,
  `creator` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_events_users1_idx` (`creator` ASC),
  CONSTRAINT `event_ownership`
    FOREIGN KEY (`creator`)
    REFERENCES `meteocal`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meteocal`.`calendars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meteocal`.`calendars` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `owner` INT NOT NULL,
  `public` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_calendars_users1_idx` (`owner` ASC),
  UNIQUE INDEX `owner_UNIQUE` (`owner` ASC),
  CONSTRAINT `calendar_ownership`
    FOREIGN KEY (`owner`)
    REFERENCES `meteocal`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meteocal`.`participations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meteocal`.`participations` (
  `event` INT NOT NULL,
  `calendars_id` INT NOT NULL,
  `accepted` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`event`, `calendars_id`),
  INDEX `fk_events_has_users_events1_idx` (`event` ASC),
  INDEX `fk_event_participations_calendars1_idx` (`calendars_id` ASC),
  CONSTRAINT `events_participations`
    FOREIGN KEY (`event`)
    REFERENCES `meteocal`.`events` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `calendars_participations`
    FOREIGN KEY (`calendars_id`)
    REFERENCES `meteocal`.`calendars` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meteocal`.`notifications_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meteocal`.`notifications_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meteocal`.`notifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meteocal`.`notifications` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `events_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  `notifications_type` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_notifications_events1_idx` (`events_id` ASC),
  INDEX `fk_notifications_users1_idx` (`users_id` ASC),
  INDEX `fk_notifications_notifications_types1_idx` (`notifications_type` ASC),
  CONSTRAINT `event_notifications`
    FOREIGN KEY (`events_id`)
    REFERENCES `meteocal`.`events` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `user_notifications`
    FOREIGN KEY (`users_id`)
    REFERENCES `meteocal`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `notification_type`
    FOREIGN KEY (`notifications_type`)
    REFERENCES `meteocal`.`notifications_types` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meteocal`.`weather_conditions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meteocal`.`weather_conditions` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `icon` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meteocal`.`cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meteocal`.`cities` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `lat` DOUBLE NOT NULL,
  `lon` DOUBLE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meteocal`.`forecasts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meteocal`.`forecasts` (
  `dt` DATETIME NOT NULL,
  `city` INT NOT NULL,
  `temp_min` DOUBLE NOT NULL,
  `temp_max` DOUBLE NOT NULL,
  `pressure` DOUBLE NOT NULL,
  `humidity` DOUBLE NOT NULL,
  `weather_condition` INT NOT NULL,
  INDEX `fk_forecasts_weather_conditions1_idx` (`weather_condition` ASC),
  INDEX `fk_forecasts_cities1_idx` (`city` ASC),
  PRIMARY KEY (`dt`, `city`),
  CONSTRAINT `forecast_conditions`
    FOREIGN KEY (`weather_condition`)
    REFERENCES `meteocal`.`weather_conditions` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `city_forecasts`
    FOREIGN KEY (`city`)
    REFERENCES `meteocal`.`cities` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meteocal`.`events_forecasts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `meteocal`.`events_forecasts` (
  `events_id` INT NOT NULL,
  `forecasts_city` INT NOT NULL,
  `forecasts_dt` DATETIME NOT NULL,
  PRIMARY KEY (`events_id`, `forecasts_city`, `forecasts_dt`),
  INDEX `fk_events_has_forecasts_forecasts1_idx` (`forecasts_city` ASC, `forecasts_dt` ASC),
  INDEX `fk_events_has_forecasts_events1_idx` (`events_id` ASC),
  CONSTRAINT `fk_events_has_forecasts_events1`
    FOREIGN KEY (`events_id`)
    REFERENCES `meteocal`.`events` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_events_has_forecasts_forecasts1`
    FOREIGN KEY (`forecasts_city` , `forecasts_dt`)
    REFERENCES `meteocal`.`forecasts` (`city` , `dt`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;




INSERT INTO meteocal.notifications_types (`name`, description) 
	VALUES ('Event Creation', 'You''ve been invited to the event %s by %s. Link to the event: ');
INSERT INTO meteocal.notifications_types (`name`, description) 
	VALUES ('Bad Weather - 3 Days', 'For your event %s the forecast reports bad weather. We found the first available sunny day to be on %s. Edit your event at: ');
INSERT INTO meteocal.notifications_types (`name`, description) 
	VALUES ('Bad Weather - 3 Days - No sunny days', 'For your event %s the forecast reports bad weather. Unfortunately there isn''t any sunny day for the next days.');
INSERT INTO meteocal.notifications_types (`name`, description) 
	VALUES ('Bad Weather - Tomorrow!', 'There''s bad weather for your tomorrow event %s!');
INSERT INTO meteocal.notifications_types (`name`, description) 
    VALUES ('Forecast change', 'The forecast for the event you''re participating %s is changed! Check it out: ');


INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('200', 'Thunderstorm', 'thunderstorm with light rain', '11d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('201', 'Thunderstorm', 'thunderstorm with rain', '11d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('202', 'Thunderstorm', 'thunderstorm with heavy rain', '11d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('210', 'Thunderstorm', 'light thunderstorm', '11d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('211', 'Thunderstorm', 'thunderstorm', '11d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('212', 'Thunderstorm', 'heavy thunderstorm', '11d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('221', 'Thunderstorm', 'ragged thunderstorm', '11d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('230', 'Thunderstorm', 'thunderstorm with light drizzle', '11d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('231', 'Thunderstorm', 'thunderstorm with drizzle', '11d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('232', 'Thunderstorm', 'thunderstorm with heavy drizzle', '11d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('300', 'Drizzle', 'light intensity drizzle', '09d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('301', 'Drizzle', 'drizzle', '09d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('302', 'Drizzle', 'heavy intensity drizzle', '09d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('310', 'Drizzle', 'light intensity drizzle rain', '09d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('311', 'Drizzle', 'drizzle rain', '09d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('312', 'Drizzle', 'heavy intensity drizzle rain', '09d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('313', 'Drizzle', 'shower rain and drizzle', '09d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('314', 'Drizzle', 'heavy shower rain and drizzle', '09d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('321', 'Drizzle', 'shower drizzle', '09d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('500', 'Rain', 'light rain', '10d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('501', 'Rain', 'moderate rain', '10d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('502', 'Rain', 'heavy intensity rain', '10d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('503', 'Rain', 'very heavy rain', '10d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('504', 'Rain', 'extreme rain', '10d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('511', 'Rain', 'freezing rain', '13d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('520', 'Rain', 'light intensity shower rain', '09d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('521', 'Rain', 'shower rain', '09d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('522', 'Rain', 'heavy intensity shower rain', '09d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('531', 'Rain', 'ragged shower rain', '09d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('600', 'Snow', 'light snow', '13d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('601', 'Snow', 'snow', '13d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('602', 'Snow', 'heavy snow', '13d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('611', 'Snow', 'sleet', '13d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('612', 'Snow', 'shower sleet', '13d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('615', 'Snow', 'light rain and snow', '13d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('616', 'Snow', 'rain and snow', '13d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('620', 'Snow', 'light shower snow', '13d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('621', 'Snow', 'shower snow', '13d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('622', 'Snow', 'heavy shower snow', '13d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('701', 'Atmosphere', 'mist', '50d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('711', 'Atmosphere', 'smoke', '50d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('721', 'Atmosphere', 'haze', '50d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('731', 'Atmosphere', 'sand, dust whirls', '50d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('741', 'Atmosphere', 'fog', '50d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('751', 'Atmosphere', 'sand', '50d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('761', 'Atmosphere', 'dust', '50d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('762', 'Atmosphere', 'volcanic ash', '50d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('771', 'Atmosphere', 'squalls', '50d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('781', 'Atmosphere', 'tornado', '50d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('800', 'Clouds', 'clear sky', '01d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('801', 'Clouds', 'few clouds', '02d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('802', 'Clouds', 'scattered clouds', '03d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('803', 'Clouds', 'broken clouds', '04d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('804', 'Clouds', 'overcast clouds', '04d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('900', 'Extreme', 'tornado', 'NULL');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('901', 'Extreme', 'tropical storm', 'NULL');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('902', 'Extreme', 'hurricane', 'NULL');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('903', 'Extreme', 'cold', 'NULL');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('904', 'Extreme', 'hot', 'NULL');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('905', 'Extreme', 'windy', 'NULL');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('906', 'Extreme', 'hail', 'NULL');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('951', 'Additional', 'calm', 'NULL');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('952', 'Additional', 'light breeze', 'NULL');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('953', 'Additional', 'gentle breeze', 'NULL');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('954', 'Additional', 'moderate breeze', 'NULL');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('955', 'Additional', 'fresh breeze', 'NULL');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('956', 'Additional', 'strong breeze', 'NULL');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('957', 'Additional', 'high wind, near gale', 'NULL');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('958', 'Additional', 'gale', 'NULL');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('959', 'Additional', 'severe gale', 'NULL');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('960', 'Additional', 'storm', 'NULL');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('961', 'Additional', 'violent storm', 'NULL');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('962', 'Additional', 'hurricane', 'NULL');
