INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('200', 'Thunderstorm', 'thunderstorm with light rain', '11d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('201', 'Thunderstorm', 'thunderstorm with rain', '11d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('202', 'Thunderstorm', 'thunderstorm with heavy rain', '11d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('210', 'Thunderstorm', 'light thunderstorm', '11d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('211', 'Thunderstorm', 'thunderstorm', '11d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('212', 'Thunderstorm', 'heavy thunderstorm', '11d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('221', 'Thunderstorm', 'ragged thunderstorm', '11d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('230', 'Thunderstorm', 'thunderstorm with light drizzle', '11d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('231', 'Thunderstorm', 'thunderstorm with drizzle', '11d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('232', 'Thunderstorm', 'thunderstorm with heavy drizzle', '11d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('300', 'Drizzle', 'light intensity drizzle', '09d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('301', 'Drizzle', 'drizzle', '09d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('302', 'Drizzle', 'heavy intensity drizzle', '09d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('310', 'Drizzle', 'light intensity drizzle rain', '09d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('311', 'Drizzle', 'drizzle rain', '09d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('312', 'Drizzle', 'heavy intensity drizzle rain', '09d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('313', 'Drizzle', 'shower rain and drizzle', '09d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('314', 'Drizzle', 'heavy shower rain and drizzle', '09d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('321', 'Drizzle', 'shower drizzle', '09d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('500', 'Rain', 'light rain', '10d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('501', 'Rain', 'moderate rain', '10d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('502', 'Rain', 'heavy intensity rain', '10d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('503', 'Rain', 'very heavy rain', '10d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('504', 'Rain', 'extreme rain', '10d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('511', 'Rain', 'freezing rain', '13d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('520', 'Rain', 'light intensity shower rain', '09d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('521', 'Rain', 'shower rain', '09d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('522', 'Rain', 'heavy intensity shower rain', '09d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('531', 'Rain', 'ragged shower rain', '09d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('600', 'Snow', 'light snow', '13d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('601', 'Snow', 'snow', '13d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('602', 'Snow', 'heavy snow', '13d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('611', 'Snow', 'sleet', '13d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('612', 'Snow', 'shower sleet', '13d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('615', 'Snow', 'light rain and snow', '13d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('616', 'Snow', 'rain and snow', '13d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('620', 'Snow', 'light shower snow', '13d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('621', 'Snow', 'shower snow', '13d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('622', 'Snow', 'heavy shower snow', '13d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('701', 'Atmosphere', 'mist', '50d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('711', 'Atmosphere', 'smoke', '50d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('721', 'Atmosphere', 'haze', '50d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('731', 'Atmosphere', 'sand, dust whirls', '50d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('741', 'Atmosphere', 'fog', '50d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('751', 'Atmosphere', 'sand', '50d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('761', 'Atmosphere', 'dust', '50d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('762', 'Atmosphere', 'volcanic ash', '50d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('771', 'Atmosphere', 'squalls', '50d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('781', 'Atmosphere', 'tornado', '50d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('800', 'Clouds', 'clear sky', '01d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('801', 'Clouds', 'few clouds', '02d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('802', 'Clouds', 'scattered clouds', '03d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('803', 'Clouds', 'broken clouds', '04d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('804', 'Clouds', 'overcast clouds', '04d');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('900', 'Extreme', 'tornado', 'NULL');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('901', 'Extreme', 'tropical storm', 'NULL');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('902', 'Extreme', 'hurricane', 'NULL');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('903', 'Extreme', 'cold', 'NULL');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('904', 'Extreme', 'hot', 'NULL');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('905', 'Extreme', 'windy', 'NULL');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('906', 'Extreme', 'hail', 'NULL');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('951', 'Additional', 'calm', 'NULL');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('952', 'Additional', 'light breeze', 'NULL');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('953', 'Additional', 'gentle breeze', 'NULL');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('954', 'Additional', 'moderate breeze', 'NULL');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('955', 'Additional', 'fresh breeze', 'NULL');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('956', 'Additional', 'strong breeze', 'NULL');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('957', 'Additional', 'high wind, near gale', 'NULL');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('958', 'Additional', 'gale', 'NULL');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('959', 'Additional', 'severe gale', 'NULL');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('960', 'Additional', 'storm', 'NULL');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('961', 'Additional', 'violent storm', 'NULL');
INSERT INTO `meteocal`.`weather_conditions` (`id`, `name`, `description`, `icon`) VALUES ('962', 'Additional', 'hurricane', 'NULL');
